CSC8503CoreClasses/ILevelManager.h
CSC8503CoreClasses/LevelManager.cpp
CSC8503CoreClasses/LevelManager.h

Updating CTP-88 Branch to master, forgot to fetch before creating branch.

Updating Branch

---

CSC8503CoreClasses/RenderObject.cpp

ooooooooops
fixed the merge I added that broke the build :(

fixes to RenderObject.cpp

---

CSC8503CoreClasses/CMakeLists.txt
CSC8503CoreClasses/GuardObject.cpp
CSC8503CoreClasses/JsonParser.cpp
CSC8503CoreClasses/JsonParser.h
CSC8503CoreClasses/Level.cpp
CSC8503CoreClasses/Level.h
CSC8503CoreClasses/LevelEnums.cpp
CSC8503CoreClasses/LevelEnums.h
CSC8503CoreClasses/LevelManager.h
CSC8503CoreClasses/Room.cpp
CSC8503CoreClasses/Room.h

Added JSON parsing for room objects, as well as cleaning up a large amount of what was done with Level.
There's a lot of "new" lines but a lot of it is me moving around where things were.

Level/CTP-109 assigning of room class from JSON

---

CSC8503/TutorialGame.cpp
CSC8503CoreClasses/GameObject.h

Urgent to review!! fix master branch

fixing master branch

---

CSC8503/SuspicionSystem/SuspicionMetre.cpp
CSC8503/SuspicionSystem/SuspicionMetre.h

But also myself, but also im tired, im so sorry about this

I hate Github

---

CSC8503/SuspicionSystem/GlobalSuspicionMetre.cpp
CSC8503/SuspicionSystem/GlobalSuspicionMetre.h

The global suspicion metre required by the suspicion system

Global Suspicion Metre Added

---

OpenGLRendering/OGLRenderer.h
OpenGLRendering/glad/gl.h

We may have inherited something that breaks everything, not sure, but at least it's fixed for now.

Fix Master

---

CSC8503/CMakeLists.txt
CSC8503/InventoryBuffSystem/PickupGameObject.cpp
CSC8503/InventoryBuffSystem/PickupGameObject.h

Sidenote- I can't use setActive, as that pauses the updating of the state machine

PickupGameObject base

---

CSC8503/InventoryBuffSystem/InventoryBuffSystem.h
CSC8503/InventoryBuffSystem/PlayerInventory.h

I guess that was all that was needed to be done, huh

mPlayerInventoryPtr fix

---

CSC8503/InventoryBuffSystem/PlayerInventory.h

This is a quick fix to get it to compile, but i think this needs a closer look

fix to get it to compile

---

CSC8503/InventoryBuffSystem/PlayerBuffs.cpp
CSC8503/InventoryBuffSystem/PlayerBuffs.h
CSC8503/InventoryBuffSystem/PlayerInventory.cpp
CSC8503/InventoryBuffSystem/PlayerInventory.h
CSC8503/SuspicionSystem/GlobalSuspicionMetre.h
CSC8503/SuspicionSystem/LocalSuspicionMetre.cpp
CSC8503/SuspicionSystem/LocalSuspicionMetre.h
CSC8503/SuspicionSystem/LocationBasedSuspicion.h
CSC8503CoreClasses/Level.cpp
CSC8503CoreClasses/Level.h

ConstVarFix

---

CSC8503/GameTechRenderer.cpp
CSC8503/Main.cpp

Quick pr to un-comment out the stuff that renders debug text

Fixing debug stuff

---

CSC8503/CMakeLists.txt
CSC8503/Scene.cpp
CSC8503/Scene.h

- Added the abstract "Scene" class.

UI-And-Menus/CTP-173-Create-Base-Scene

---

CSC8503/InventoryBuffSystem/PlayerInventory.h
CSC8503/LevelManager.cpp

Seriously though, this broke my code

This was a breach of my privacy

---

CSC8503/LevelManager.cpp
CSC8503CoreClasses/PrisonDoor.cpp

Level/Add Item Add Loop To Game

---

CSC8503/GameSceneManager.cpp
CSC8503/LevelManager.cpp
CSC8503/LevelManager.h
CSC8503CoreClasses/PhysicsSystem.cpp
CSC8503CoreClasses/QuadTree.h

Further efficiency changes

---

CSC8503/AlertSystem.h
CSC8503CoreClasses/AnimationSystem.cpp

Animation list create in LoadLevel now.

Cpt 224 implement the alert system in game(Fix bug)

---

CSC8503CoreClasses/AnimationSystem.cpp
CSC8503CoreClasses/GameObject.cpp
CSC8503CoreClasses/GameObject.h
CSC8503CoreClasses/GuardObject.cpp
CSC8503CoreClasses/GuardObject.h
CSC8503CoreClasses/PlayerObject.cpp
CSC8503CoreClasses/PlayerObject.h

Uniform PlayerState and GuardState to GameObjectState
Animation change by GmeObjectState now

Uniform PlayerState and GuardState to GameObjectState

---

CSC8503CoreClasses/Vent.cpp

Now places player correctly without need for offset and rotates player away from vent.

Level/Update Vent Functionality

---

CSC8503/GameTechRenderer.cpp
CSC8503/GameTechRenderer.h
CSC8503/LevelManager.cpp
CSC8503/LevelManager.h

Level/CTP-325 Instance EG2 Asset Loading

---

CSC8503/LevelManager.cpp
CSC8503/LevelManager.h
CSC8503/NetworkPlayer.cpp
CSC8503CoreClasses/PlayerObject.cpp
CSC8503CoreClasses/PlayerObject.h

Suspicion system pointer used to be nullptr for network player, now fixed
Similar problem found with the UI. Fixed

Fixed multiplayer suspicion system bug

---

Assets/Shaders/UI.frag
CSC8503/LevelManager.cpp
CSC8503/LevelManager.h
CSC8503CoreClasses/PlayerObject.cpp
CSC8503CoreClasses/PlayerObject.h
CSC8503CoreClasses/UISystem.cpp
CSC8503CoreClasses/UISystem.h

Linear interpolation optimization

---

CSC8503CoreClasses/GameWorld.cpp
CSC8503CoreClasses/GuardObject.cpp
CSC8503CoreClasses/Helipad.cpp
CSC8503CoreClasses/InteractableDoor.cpp
CSC8503CoreClasses/PlayerObject.cpp

More PS5 fixes and code decided to stop compiling despite no changes

More PS5 fixes and code decided to stop compiling despite no changes

---

CSC8503CoreClasses/InteractableDoor.cpp
CSC8503CoreClasses/PlayerObject.cpp

For real last PS5 changes

---

CSC8503CoreClasses/AABBVolume.h
CSC8503CoreClasses/CapsuleVolume.h
CSC8503CoreClasses/CollisionVolume.h
CSC8503CoreClasses/OBBVolume.h
CSC8503CoreClasses/PhysicsSystem.cpp
CSC8503CoreClasses/PhysicsSystem.h
CSC8503CoreClasses/QuadTree.h
CSC8503CoreClasses/SphereVolume.h

We back to 60fps now and we're now bottlenecked by the Rendered and GPU \o/

CTP-290 Make QuadTree Faster

---

CSC8503CoreClasses/GameObject.h
CSC8503CoreClasses/GuardObject.cpp
CSC8503CoreClasses/GuardObject.h
Detour/Source/DetourNavMeshQuery.cpp

Tweaked guard behaviour and added support for pointing

Improved upon the guard's behaviour

---

CSC8503/GameSceneManager.cpp
CSC8503/LevelManager.cpp
CSC8503CoreClasses/GuardObject.cpp

Player raycasting fixed

---

CSC8503/LevelManager.cpp
CSC8503CoreClasses/JsonParser.cpp
CSC8503CoreClasses/JsonParser.h

This should be easier to read and faster

Level/CTP-372 Refactor JsonParser to use function map

---

.gitignore
CSC8503/LevelManager.cpp
CSC8503/LevelManager.h
CSC8503/Main.cpp

Can see:
FPS (kind of need to figure out a cleaner method)
Memory Usage
CPU Usage
Method timing

UI and menus/CTP 381 create toggleable debug state

---

CSC8503/DebugNetworkedGame.cpp
CSC8503/InventoryBuffSystem/FlagGameObject.cpp
CSC8503/SuspicionSystem/LocalSuspicionMetre.cpp
CSC8503/SuspicionSystem/LocationBasedSuspicion.cpp
CSC8503/SuspicionSystem/LocationBasedSuspicion.h
CSC8503CoreClasses/CCTV.cpp
CSC8503CoreClasses/GameClient.cpp
CSC8503CoreClasses/GameClient.h
CSC8503CoreClasses/PlayerObject.cpp
CSC8503CoreClasses/PlayerObject.h

Now adds a location based suspicion value on its position if it did not already have it
Sus meter UI Fix and changes
Client->Server location based suspicion
Fixed flag bug w full inventory

CCTV additions and other changes

---

CSC8503/DebugNetworkedGame.cpp
CSC8503/LevelManager.h

multiple color of players
